package com.lisy.admin.dao;

import com.lisy.admin.model.AdminLog;
import java.util.List;

public interface AdminLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int insert(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    AdminLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    List<AdminLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminLog record);
}