spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# 热部署开关，false即不启用热部署
  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
